version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:root@db:5432/crud'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuxt-frontend
    ports:
      - '5000:3000'
    environment:
      API_URL: 'http://localhost:5000'

  db:
    image: postgres:13
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crud
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
